version: '3.8'

services:
  api:
    container_name: ${CONTAINER_API_NAME}
    build:
      context: .
      dockerfile: api.dockerfile
    image: BACKEND_API
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/api
    networks:
      - base_network
    depends_on:
      - mysql
    command: npx prisma migrate deploy && npm start

  mysql:
    container_name: ${CONTAINER_BD_NAME}
    image: mysql:latest
    ports:
      - ${PORT_DB}:${PORT_DB}
    expose:
      - ${PORT_DB}
    volumes:
      - MYSQL_VOLUME_BD:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    


networks:
  base_network:
    driver: bridge

volumes:
  MYSQL_VOLUME_BD: