services:
  api:
    container_name: ${CONTAINER_API_NAME}
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - ${PORT_APP}:${PORT_APP}
    volumes:
      - ./:/api
    networks:
      - base_network
    depends_on:
      - mysql
    command: sh -c "npx prisma migrate deploy && npm start"

  mysql:
    container_name: ${CONTAINER_BD_NAME}
    image: mysql:latest
    ports:
      - ${PORT_DB}:${PORT_DB}
    expose:
      - ${PORT_DB}
    volumes:
      - mysql_volume_bd:/var/lib/mysql
    networks:
      - base_network
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    

networks:
  base_network:
    driver: bridge


volumes:
  mysql_volume_bd: